FROM maven:3.5-jdk-8-alpine as builder

COPY src /usr/src/app/src
COPY pom.xml /usr/src/app

RUN mvn -f /usr/src/app/pom.xml clean package

ENTRYPOINT ["java", "-cp", "/usr/src/app/target/my-app-1.0-SNAPSHOT.jar", "com.mycompany.app.App"]
