FROM docker.io/library/nginx-centos7
LABEL "io.k8s.display-name"="nginx-centos7-app" \
      "io.openshift.s2i.build.image"="docker.io/library/nginx-centos7" \
      "io.openshift.s2i.build.source-location"="test/test-app"

USER root
# Copying in source code
COPY upload/src /tmp/src
# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/src
USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN /usr/libexec/s2i/assemble
# Run script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
CMD /usr/libexec/s2i/run
